language: node_js
node_js:
  - node
install:
  - npm ci

jobs:
  include:
    - stage: unit tests
      script: npm run test
    - stage: functional tests
      script: $(npm bin)/cypress run
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: hidalgo-city-explorer
        api_key: HEROKU_AUTH_TOKEN