language: node_js
node_js:
- node
install:
- npm ci
jobs:
  include:
  - stage: tests
    script:
    - npm run test
    - $(npm bin)/cypress run
  - stage: deploy to staging
    script: skip
    deploy:
      provider: heroku
      app: hidalgo-city-explorer
      api_key: $HEROKU_AUTH_TOKEN
