language: node_js
node_js:
- node
install:
- npm ci
branches:
  only:
    - development
    - staging
    - master
jobs:
  include:
  - stage: unit tests
    script:
      - npm run test
    after_success:
      - npm run coverage
  - stage: deploy to development
    if: branch = development
    script: skip
    deploy:
        provider: heroku
        app: hidalgo-city-explorer
        api_key: $HEROKU_AUTH_TOKEN
        on: development
  - stage: deploy to staging
    if: branch = staging
    script: skip
    deploy:
      provider: heroku
      app: hidalgo-city-explorer-staging
      api_key: $HEROKU_AUTH_TOKEN
      on: staging
  - stage: deploy to production
    if: branch = master
    script: skip
    deploy:
        provider: heroku
        app: hidalgo-city-explorer-prod
        api_key: $HEROKU_AUTH_TOKEN
        on: master
  - stage: functional tests
    script:
      - CYPRESS_baseUrl=$CYPRESS_URL $(npm bin)/cypress run
notifications:
  email:
    recipients:
      - $EMAIL
    on_failure: always # default: always
